addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.0.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.9")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.5.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"              % "3.9.2")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"                   % "2.0.0-M2")
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.2")
